In [ ]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
my_array = np.array(my_list)

In [5]:
my_list

[1, 2, 3]

In [6]:
my_array

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_np_mat = np.array(my_matrix)

In [10]:
my_np_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,100,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [7]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(5,2)

array([[0.57614496, 0.61454611],
       [0.12438539, 0.29490597],
       [0.08514583, 0.9949409 ],
       [0.45495714, 0.83585022],
       [0.62052762, 0.66532217]])

In [21]:
np.random.randn(5,2)

array([[-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024]])

In [23]:
np.random.randint(0,100,20)

array([89, 52,  1, 83, 91, 59, 70, 43,  7, 46, 34, 77, 80, 35, 49,  3,  1,
        5, 53,  3])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
arr = np.arange(0,25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
my_arr = np.random.randint(1,100,100)

In [37]:
my_arr

array([68, 58, 75, 29, 36, 89, 21, 36, 10, 73, 24, 64, 99, 49, 99, 36, 82,
       96, 24, 23, 62, 96, 37, 12, 55, 13, 23, 89, 99, 30, 17, 62, 84, 89,
       86, 13, 59, 19, 49, 12, 61, 19, 76,  9, 71, 28, 78, 95, 52, 83, 16,
       69, 99, 12, 25, 52, 85, 53, 23, 16, 57, 39, 53, 42, 58, 39, 14, 95,
        5, 35, 87, 93, 75, 18, 76,  9, 74, 58, 17,  7, 46, 13, 40, 42,  9,
       50, 27, 66,  5, 29, 37, 38, 83,  8, 65, 86, 17, 71, 89, 45])

In [33]:
my_arr.max()

99

In [34]:
my_arr.min()


5

In [35]:
my_arr.argmax()

12

In [36]:
my_arr.argmin()

68

In [41]:
myarr = np.linspace(0,10,101)

In [42]:
len(myarr)

101