### Import Libraries

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt


### Read Dataset

In [3]:
dataset = pd.read_csv('~/Documents/interview/data/Position_Salaries.csv')
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1:].values

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
print(y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [6]:
type(x)

numpy.ndarray

In [7]:
print(x)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [8]:
dataset.head()

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [9]:
dataset.shape

(10, 3)

In [10]:
dataset.isna().sum()

Position    0
Level       0
Salary      0
dtype: int64

### Train Test Split

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y,train_size=0.8,random_state=1)

In [12]:
print(X_train)

[[7]
 [5]
 [1]
 [4]
 [2]
 [8]
 [9]
 [6]]


In [15]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x,y)

LinearRegression()

In [18]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2)
x_poly = pf.fit_transform(x)
